### ISSUE TITLE
Kinesalite docker image broken?

### ISSUE THREAD

**Issue by Oliver-Sellwood** [instructure/dockerfiles#10]
Hey, 

Our CI pipeline is broken and I'm getting this error

```
kinesis_1       | 
kinesis_1       | /usr/src/app/node_modules/levelup/lib/levelup.js:119
kinesis_1       |       return callback(new OpenError(err))
kinesis_1       |                       ^
kinesis_1       | OpenError: IO error: /var/lib/kinesalite/LOCK: Permission denied
kinesis_1       |     at /usr/src/app/node_modules/levelup/lib/levelup.js:119:23
kinesis_1       |     at /usr/src/app/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
kinesis_1       |     at /usr/src/app/node_modules/deferred-leveldown/deferred-leveldown.js:31:21
kinesis_1       |     at /usr/src/app/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
kinesis_1       | Emitted 'error' event at:
kinesis_1       |     at /usr/src/app/node_modules/levelup/lib/levelup.js:60:19
kinesis_1       |     at /usr/src/app/node_modules/levelup/lib/levelup.js:119:14
kinesis_1       |     at /usr/src/app/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
kinesis_1       |     at /usr/src/app/node_modules/deferred-leveldown/deferred-leveldown.js:31:21
kinesis_1       |     at /usr/src/app/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
```

It was all working fine before the weekend so maybe something to do with the golang 1.17 update?

**Comment by Oliver-Sellwood** [comment]
And it's working again today! 

Closing.

Thanks :)
